export const dict = {
  'home' : 'خانه',
  'name' : 'نام و نام خانوادگی ',
  'login' : 'ورود',
  'username' :  'شماره موبایل (مثلا ۰۹۱۲۳۴۵۶۷۸۹)',
  'password' : 'رمز عبور ',
  'password_confirmation': 'تکرار رمز عبور',
  'mobile' : 'شماره موبایل ',
  'error': 'خطا',
  'sign_in' : 'ورود ',
  'sign_up' : 'ثبت نام',
  'back' : 'بازگشت',
  'signed_up_already': 'تا کنون ثبت نام نکرده اید؟',
  'new_advert': 'درج آگهی ',
  'title': 'عنوان',
  'content': 'متن آگهی',
  'submit': 'ثبت ',
  'upload_from_camera' : 'عکس با دوربین',
  'upload_from_gallery': 'انتخاب از گالری',
  'welcome': 'خوش آمدید',
  'sign_out': 'خروج',
  'phone_number': 'شماره تلفن',
  'telegram_channel': 'کانال تلگرام',
  'instagram_page': 'صفحه اینستاگرام',
  'address': 'آدرس ',
  'email': 'ایمیل ',
  'contact_information':'اطلاعات تماس ',
  'search': 'جستجو ',
  'cancel' : 'بیخیال',
  'view': 'نمایش',
  'edit': 'ویرایش',
  'delete': 'حذف',
  'adverts_nes': 'عنوان، متن و شماره تلفن اجباری است',
  'my_advertisements': 'آگهی های من',
  'my_pins': ' نشان شده‌ها ',
  'pin' : 'نشان کن',
  'pinned': 'نشان شده',
  'message_to_seller': 'ارسال پیام',
  'messages': 'پیام ها ',
  'send_message': 'پیام خود را بنویسید',
  'conversations_on_other_ads': 'پیام ها بر روی آگهی های دیگران',
  'conversations_on_your_ads': 'پیام ها بر آگهی های شما',
  'province': 'استان',
  'city': 'شهر',
  'website': 'وبسایت',
  'call': 'تماس بگیرید',
  'price': 'قیمت ',
  'uploading_in_progress': ' بارگذاری عکس  در حال انجام است. آیا می خواهید به هر ترتیب ارسال شود.',
  'ago': 'قبل ',
  'all_above': 'همه ی موارد فوق',
  'no_result': 'موردی یافت نشد ',
  'category': 'دسته بندی ',
  'departure':'رفت',
  'arrival': 'برگشت',
  'price_range': 'بازه قیمت ',
  'accomodation': 'اقامت',
  'stars': 'ستاره ',
  'hotel_name': 'نام هتل ',
  'duration': 'مدت اقامت ',
  'transportation': 'حمل و نقل ',
  'transportation_type': 'نوع',
  'company':'شرکت ',
  'leg':'مسیر',
  'date':'تاریخ',
  'time': 'زمان',
  'pricings':'قیمت ها ',
  'tour_detail': 'شرح ',
  'reservation': 'رزرو',
  'numberOfPassngers': 'تعداد مسافران ',
  'surename': 'نام خانوادگی',
  'fathername':'نام پدر',
  'ssn':'کدملی',
  'birthplace':'محل تولد',
  'pass_no': 'شماره گذرنامه',
  'birthdate': 'تاریخ تولد',
  'place_of_birth': 'محل تولد',
  'required_fields': 'فیلدهای اجباری',
  'en_father_name': 'نام پدر لاتین',
  'en_name': 'نام لاتین',
  'en_surename': 'نام خانوادگی لاتین ',
  'passport_no': 'شماره گذرنامه',
  'final_confirm' : 'تایید نهایی ',
  'my_reservations': 'رزرو شده ها ',
  'verified_reservations': 'رزرو شده  ها ',
  'remained_capacity': 'ظرفیت باقی مانده',
  'person' : 'نفر '
};
