export const dict = {
  'home' : 'خانه',
  'name' : 'نام',
  'login' : 'ورود',
  'username' : 'شماره موبایل',
  'password' : 'رمز عبور ',
  'password_confirmation': 'تکرار رمز عبور',
  'mobile' : 'شماره موبایل ',
  'error': 'خطا',
  'sign_in' : 'ورود ',
  'sign_up' : 'ثبت نام',
  'back' : 'بازگشت',
  'signed_up_already': 'تا کنون ثبت نام نکرده اید؟',
  'new_advert': 'درج آگهی ',
  'title': 'عنوان آگهی',
  'content': 'متن آگهی',
  'submit': 'ثبت ',
  'upload_from_camera' : 'عکس با دوربین',
  'upload_from_gallery': 'انتخاب از گالری',
  'welcome': 'خوش آمدید',
  'sign_out': 'خروج',
  'phone_number': 'شماره تلفن',
  'telegram_channel': 'کانال تلگرام',
  'instagram_page': 'صفحه اینستاگرام',
  'address': 'آدرس ',
  'email': 'ایمیل ',
  'contact_information':'اطلاعات تماس ',
  'search': 'جستجو ',
  'cancel' : 'بیخیال',
  'view': 'نمایش',
  'edit': 'ویرایش',
  'delete': 'حذف'
};
